-- Наполнение справочника железа.
--
-- Список моделей от владельца: видеокарты, процессоры, память, мониторы, мыши,
-- клавиатуры, гарнитуры и кресла. Мониторы идут с частотой в meta — при выборе
-- монитора герцовка подставляется в зону сама.
--
-- on conflict do nothing: миграцию можно прогнать повторно, дублей не будет.

insert into public.hardware_catalog (kind, brand, model, meta, sort_order) values
  ('gpu', 'NVIDIA', 'RTX 4060', '{}'::jsonb, 10),
  ('gpu', 'NVIDIA', 'RTX 4060 Ti 8 GB', '{}'::jsonb, 20),
  ('gpu', 'NVIDIA', 'RTX 4060 Ti 16 GB', '{}'::jsonb, 30),
  ('gpu', 'NVIDIA', 'RTX 4070', '{}'::jsonb, 40),
  ('gpu', 'NVIDIA', 'RTX 4070 SUPER', '{}'::jsonb, 50),
  ('gpu', 'NVIDIA', 'RTX 4070 Ti', '{}'::jsonb, 60),
  ('gpu', 'NVIDIA', 'RTX 4070 Ti SUPER', '{}'::jsonb, 70),
  ('gpu', 'NVIDIA', 'RTX 4080', '{}'::jsonb, 80),
  ('gpu', 'NVIDIA', 'RTX 4080 SUPER', '{}'::jsonb, 90),
  ('gpu', 'NVIDIA', 'RTX 4090', '{}'::jsonb, 100),
  ('gpu', 'NVIDIA', 'RTX 5050', '{}'::jsonb, 110),
  ('gpu', 'NVIDIA', 'RTX 5060', '{}'::jsonb, 120),
  ('gpu', 'NVIDIA', 'RTX 5060 Ti 8 GB', '{}'::jsonb, 130),
  ('gpu', 'NVIDIA', 'RTX 5060 Ti 16 GB', '{}'::jsonb, 140),
  ('gpu', 'NVIDIA', 'RTX 5070', '{}'::jsonb, 150),
  ('gpu', 'NVIDIA', 'RTX 5070 Ti', '{}'::jsonb, 160),
  ('gpu', 'NVIDIA', 'RTX 5080', '{}'::jsonb, 170),
  ('gpu', 'NVIDIA', 'RTX 5090', '{}'::jsonb, 180),
  ('cpu', 'Intel', 'Core i5-12400', '{}'::jsonb, 190),
  ('cpu', 'Intel', 'Core i5-12400F', '{}'::jsonb, 200),
  ('cpu', 'Intel', 'Core i5-12490F', '{}'::jsonb, 210),
  ('cpu', 'Intel', 'Core i5-12500', '{}'::jsonb, 220),
  ('cpu', 'Intel', 'Core i5-12600', '{}'::jsonb, 230),
  ('cpu', 'Intel', 'Core i5-12600K', '{}'::jsonb, 240),
  ('cpu', 'Intel', 'Core i5-12600KF', '{}'::jsonb, 250),
  ('cpu', 'Intel', 'Core i7-12700', '{}'::jsonb, 260),
  ('cpu', 'Intel', 'Core i7-12700F', '{}'::jsonb, 270),
  ('cpu', 'Intel', 'Core i7-12700K', '{}'::jsonb, 280),
  ('cpu', 'Intel', 'Core i7-12700KF', '{}'::jsonb, 290),
  ('cpu', 'Intel', 'Core i9-12900', '{}'::jsonb, 300),
  ('cpu', 'Intel', 'Core i9-12900F', '{}'::jsonb, 310),
  ('cpu', 'Intel', 'Core i9-12900K', '{}'::jsonb, 320),
  ('cpu', 'Intel', 'Core i9-12900KF', '{}'::jsonb, 330),
  ('cpu', 'Intel', 'Core i9-12900KS', '{}'::jsonb, 340),
  ('cpu', 'Intel', 'Core i5-13400', '{}'::jsonb, 350),
  ('cpu', 'Intel', 'Core i5-13400F', '{}'::jsonb, 360),
  ('cpu', 'Intel', 'Core i5-13490F', '{}'::jsonb, 370),
  ('cpu', 'Intel', 'Core i5-13500', '{}'::jsonb, 380),
  ('cpu', 'Intel', 'Core i5-13600', '{}'::jsonb, 390),
  ('cpu', 'Intel', 'Core i5-13600K', '{}'::jsonb, 400),
  ('cpu', 'Intel', 'Core i5-13600KF', '{}'::jsonb, 410),
  ('cpu', 'Intel', 'Core i7-13700', '{}'::jsonb, 420),
  ('cpu', 'Intel', 'Core i7-13700F', '{}'::jsonb, 430),
  ('cpu', 'Intel', 'Core i7-13700K', '{}'::jsonb, 440),
  ('cpu', 'Intel', 'Core i7-13700KF', '{}'::jsonb, 450),
  ('cpu', 'Intel', 'Core i7-13790F', '{}'::jsonb, 460),
  ('cpu', 'Intel', 'Core i9-13900', '{}'::jsonb, 470),
  ('cpu', 'Intel', 'Core i9-13900F', '{}'::jsonb, 480),
  ('cpu', 'Intel', 'Core i9-13900K', '{}'::jsonb, 490),
  ('cpu', 'Intel', 'Core i9-13900KF', '{}'::jsonb, 500),
  ('cpu', 'Intel', 'Core i9-13900KS', '{}'::jsonb, 510),
  ('cpu', 'Intel', 'Core i5-14400', '{}'::jsonb, 520),
  ('cpu', 'Intel', 'Core i5-14400F', '{}'::jsonb, 530),
  ('cpu', 'Intel', 'Core i5-14490F', '{}'::jsonb, 540),
  ('cpu', 'Intel', 'Core i5-14500', '{}'::jsonb, 550),
  ('cpu', 'Intel', 'Core i5-14600', '{}'::jsonb, 560),
  ('cpu', 'Intel', 'Core i5-14600K', '{}'::jsonb, 570),
  ('cpu', 'Intel', 'Core i5-14600KF', '{}'::jsonb, 580),
  ('cpu', 'Intel', 'Core i7-14700', '{}'::jsonb, 590),
  ('cpu', 'Intel', 'Core i7-14700F', '{}'::jsonb, 600),
  ('cpu', 'Intel', 'Core i7-14700K', '{}'::jsonb, 610),
  ('cpu', 'Intel', 'Core i7-14700KF', '{}'::jsonb, 620),
  ('cpu', 'Intel', 'Core i7-14790F', '{}'::jsonb, 630),
  ('cpu', 'Intel', 'Core i9-14900', '{}'::jsonb, 640),
  ('cpu', 'Intel', 'Core i9-14900F', '{}'::jsonb, 650),
  ('cpu', 'Intel', 'Core i9-14900K', '{}'::jsonb, 660),
  ('cpu', 'Intel', 'Core i9-14900KF', '{}'::jsonb, 670),
  ('cpu', 'Intel', 'Core i9-14900KS', '{}'::jsonb, 680),
  ('cpu', 'Intel', 'Core Ultra 5 225', '{}'::jsonb, 690),
  ('cpu', 'Intel', 'Core Ultra 5 225F', '{}'::jsonb, 700),
  ('cpu', 'Intel', 'Core Ultra 5 235', '{}'::jsonb, 710),
  ('cpu', 'Intel', 'Core Ultra 5 245', '{}'::jsonb, 720),
  ('cpu', 'Intel', 'Core Ultra 5 245K', '{}'::jsonb, 730),
  ('cpu', 'Intel', 'Core Ultra 5 245KF', '{}'::jsonb, 740),
  ('cpu', 'Intel', 'Core Ultra 7 265', '{}'::jsonb, 750),
  ('cpu', 'Intel', 'Core Ultra 7 265F', '{}'::jsonb, 760),
  ('cpu', 'Intel', 'Core Ultra 7 265K', '{}'::jsonb, 770),
  ('cpu', 'Intel', 'Core Ultra 7 265KF', '{}'::jsonb, 780),
  ('cpu', 'Intel', 'Core Ultra 9 285', '{}'::jsonb, 790),
  ('cpu', 'Intel', 'Core Ultra 9 285K', '{}'::jsonb, 800),
  ('cpu', 'Intel', 'Core Ultra 5 250K Plus', '{}'::jsonb, 810),
  ('cpu', 'Intel', 'Core Ultra 5 250KF Plus', '{}'::jsonb, 820),
  ('cpu', 'Intel', 'Core Ultra 7 270K Plus', '{}'::jsonb, 830),
  ('cpu', 'AMD', 'Ryzen 5 7500F', '{}'::jsonb, 840),
  ('cpu', 'AMD', 'Ryzen 5 7600', '{}'::jsonb, 850),
  ('cpu', 'AMD', 'Ryzen 5 7600X', '{}'::jsonb, 860),
  ('cpu', 'AMD', 'Ryzen 5 7600X3D', '{}'::jsonb, 870),
  ('cpu', 'AMD', 'Ryzen 7 7700', '{}'::jsonb, 880),
  ('cpu', 'AMD', 'Ryzen 7 7700X', '{}'::jsonb, 890),
  ('cpu', 'AMD', 'Ryzen 7 7800X3D', '{}'::jsonb, 900),
  ('cpu', 'AMD', 'Ryzen 9 7900', '{}'::jsonb, 910),
  ('cpu', 'AMD', 'Ryzen 9 7900X', '{}'::jsonb, 920),
  ('cpu', 'AMD', 'Ryzen 9 7900X3D', '{}'::jsonb, 930),
  ('cpu', 'AMD', 'Ryzen 9 7950X', '{}'::jsonb, 940),
  ('cpu', 'AMD', 'Ryzen 9 7950X3D', '{}'::jsonb, 950),
  ('cpu', 'AMD', 'Ryzen 3 8300G', '{}'::jsonb, 960),
  ('cpu', 'AMD', 'Ryzen 5 8400F', '{}'::jsonb, 970),
  ('cpu', 'AMD', 'Ryzen 5 8500G', '{}'::jsonb, 980),
  ('cpu', 'AMD', 'Ryzen 5 8600G', '{}'::jsonb, 990),
  ('cpu', 'AMD', 'Ryzen 7 8700F', '{}'::jsonb, 1000),
  ('cpu', 'AMD', 'Ryzen 7 8700G', '{}'::jsonb, 1010),
  ('cpu', 'AMD', 'Ryzen 5 9600', '{}'::jsonb, 1020),
  ('cpu', 'AMD', 'Ryzen 5 9600X', '{}'::jsonb, 1030),
  ('cpu', 'AMD', 'Ryzen 5 9600X3D', '{}'::jsonb, 1040),
  ('cpu', 'AMD', 'Ryzen 7 9700X', '{}'::jsonb, 1050),
  ('cpu', 'AMD', 'Ryzen 7 9800X3D', '{}'::jsonb, 1060),
  ('cpu', 'AMD', 'Ryzen 7 9850X3D', '{}'::jsonb, 1070),
  ('cpu', 'AMD', 'Ryzen 9 9900X', '{}'::jsonb, 1080),
  ('cpu', 'AMD', 'Ryzen 9 9900X3D', '{}'::jsonb, 1090),
  ('cpu', 'AMD', 'Ryzen 9 9950X', '{}'::jsonb, 1100),
  ('cpu', 'AMD', 'Ryzen 9 9950X3D', '{}'::jsonb, 1110),
  ('cpu', 'AMD', 'Ryzen 9 9950X3D2 Dual Edition', '{}'::jsonb, 1120),
  ('ram', 'DDR4', 'DDR4 16 ГБ 3200 МГц', '{}'::jsonb, 1130),
  ('ram', 'DDR4', 'DDR4 32 ГБ 3200 МГц', '{}'::jsonb, 1140),
  ('ram', 'DDR4', 'DDR4 16 ГБ 3600 МГц', '{}'::jsonb, 1150),
  ('ram', 'DDR4', 'DDR4 32 ГБ 3600 МГц', '{}'::jsonb, 1160),
  ('ram', 'DDR5', 'DDR5 16 ГБ 5600 МГц', '{}'::jsonb, 1170),
  ('ram', 'DDR5', 'DDR5 32 ГБ 5600 МГц', '{}'::jsonb, 1180),
  ('ram', 'DDR5', 'DDR5 16 ГБ 6000 МГц', '{}'::jsonb, 1190),
  ('ram', 'DDR5', 'DDR5 32 ГБ 6000 МГц', '{}'::jsonb, 1200),
  ('monitor', 'ASUS ROG', 'ROG Swift OLED PG32UCDM — 4K', '{"hz": 240}'::jsonb, 1210),
  ('monitor', 'ASUS ROG', 'ROG Swift OLED PG32UCDM3 — 4K', '{"hz": 240}'::jsonb, 1220),
  ('monitor', 'ASUS ROG', 'ROG Swift OLED PG27UCDM — 4K', '{"hz": 240}'::jsonb, 1230),
  ('monitor', 'ASUS ROG', 'ROG Strix OLED XG27AQDMG Gen2 — QHD', '{"hz": 240}'::jsonb, 1240),
  ('monitor', 'ASUS ROG', 'ROG Strix OLED XG27AQDMES — QHD', '{"hz": 240}'::jsonb, 1250),
  ('monitor', 'ASUS ROG', 'ROG Strix OLED XG27UQDMS — 4K', '{"hz": 240}'::jsonb, 1260),
  ('monitor', 'ASUS ROG', 'ROG Strix OLED XG32UQDMS — 4K', '{"hz": 240}'::jsonb, 1270),
  ('monitor', 'ASUS ROG', 'ROG Swift OLED PG34WCDM — UWQHD', '{"hz": 240}'::jsonb, 1280),
  ('monitor', 'ASUS ROG', 'ROG Strix OLED XG34WCDMTG — UWQHD', '{"hz": 240}'::jsonb, 1290),
  ('monitor', 'ASUS ROG', 'ROG Strix OLED XG34WCDMS — UWQHD', '{"hz": 280}'::jsonb, 1300),
  ('monitor', 'ASUS ROG', 'ROG Swift PG259QN — FHD', '{"hz": 360}'::jsonb, 1310),
  ('monitor', 'ASUS ROG', 'ROG Swift PG259QNR — FHD', '{"hz": 360}'::jsonb, 1320),
  ('monitor', 'ASUS ROG', 'ROG Swift PG27AQN — QHD', '{"hz": 360}'::jsonb, 1330),
  ('monitor', 'ASUS ROG', 'ROG Strix OLED XG27ACDNG — QHD', '{"hz": 360}'::jsonb, 1340),
  ('monitor', 'ASUS ROG', 'ROG Swift OLED PG34WCDN — UWQHD', '{"hz": 360}'::jsonb, 1350),
  ('monitor', 'ASUS ROG', 'ROG Swift OLED PG27AQDP — QHD', '{"hz": 480}'::jsonb, 1360),
  ('monitor', 'ASUS ROG', 'ROG Swift OLED PG32UCDP — 4K 240 / FHD', '{"hz": 480}'::jsonb, 1370),
  ('monitor', 'ASUS ROG', 'ROG Swift OLED PG27UCWM — 4K 240 / FHD', '{"hz": 480}'::jsonb, 1380),
  ('monitor', 'ASUS ROG', 'ROG Swift OLED PG32UCWM — 4K 240 / FHD', '{"hz": 480}'::jsonb, 1390),
  ('monitor', 'ASUS ROG', 'ROG Strix OLED XG32UCWMG — 4K 240 / FHD', '{"hz": 480}'::jsonb, 1400),
  ('monitor', 'ASUS ROG', 'ROG Strix OLED XG32UQWMS — 4K 240 / FHD', '{"hz": 480}'::jsonb, 1410),
  ('monitor', 'ASUS ROG', 'ROG Strix OLED XG27AQDPG — QHD', '{"hz": 500}'::jsonb, 1420),
  ('monitor', 'ASUS ROG', 'ROG Swift OLED PG27AQDPR — QHD', '{"hz": 500}'::jsonb, 1430),
  ('monitor', 'ASUS ROG', 'ROG Swift OLED PG27AQWP-W — QHD', '{"hz": 540}'::jsonb, 1440),
  ('monitor', 'ASUS ROG', 'ROG Swift OLED PG27AQWP-G Edition 20 — QHD', '{"hz": 540}'::jsonb, 1450),
  ('monitor', 'ASUS ROG', 'ROG Swift OLED PG27AQWP-GR Edition 20 — QHD', '{"hz": 540}'::jsonb, 1460),
  ('monitor', 'Alienware', 'Alienware AW3225QF — 32" 4K', '{"hz": 240}'::jsonb, 1470),
  ('monitor', 'Alienware', 'Alienware AW2725Q — 27" 4K', '{"hz": 240}'::jsonb, 1480),
  ('monitor', 'Alienware', 'Alienware AW2726DM — 27" QHD', '{"hz": 240}'::jsonb, 1490),
  ('monitor', 'Alienware', 'Alienware AW3425DW — 34" UWQHD', '{"hz": 240}'::jsonb, 1500),
  ('monitor', 'Alienware', 'Alienware AW3426DWM — 34" UWQHD', '{"hz": 240}'::jsonb, 1510),
  ('monitor', 'Alienware', 'Alienware AW2723DF — QHD', '{"hz": 280}'::jsonb, 1520),
  ('monitor', 'Alienware', 'Alienware AW2725D — QHD', '{"hz": 280}'::jsonb, 1530),
  ('monitor', 'Alienware', 'Alienware AW2726DL — QHD', '{"hz": 280}'::jsonb, 1540),
  ('monitor', 'Alienware', 'Alienware AW3426DW — UWQHD', '{"hz": 280}'::jsonb, 1550),
  ('monitor', 'Alienware', 'Alienware AW2523HF — FHD', '{"hz": 360}'::jsonb, 1560),
  ('monitor', 'Alienware', 'Alienware AW2725DF — QHD', '{"hz": 360}'::jsonb, 1570),
  ('monitor', 'Alienware', 'Alienware AW2524HF — FHD', '{"hz": 500}'::jsonb, 1580),
  ('monitor', 'Dell', 'Dell S2522HG — FHD', '{"hz": 240}'::jsonb, 1590),
  ('monitor', 'Dell', 'Dell G2524H — FHD', '{"hz": 280}'::jsonb, 1600),
  ('monitor', 'Dell', 'Dell G2723H — FHD', '{"hz": 280}'::jsonb, 1610),
  ('monitor', 'BenQ MOBIUZ', 'MOBIUZ EX270M — FHD', '{"hz": 240}'::jsonb, 1620),
  ('monitor', 'BenQ MOBIUZ', 'MOBIUZ EX270QM — QHD', '{"hz": 240}'::jsonb, 1630),
  ('monitor', 'BenQ ZOWIE', 'ZOWIE XL2540K', '{"hz": 240}'::jsonb, 1640),
  ('monitor', 'BenQ ZOWIE', 'ZOWIE XL2546', '{"hz": 240}'::jsonb, 1650),
  ('monitor', 'BenQ ZOWIE', 'ZOWIE XL2546K', '{"hz": 240}'::jsonb, 1660),
  ('monitor', 'BenQ ZOWIE', 'ZOWIE XL2546X', '{"hz": 240}'::jsonb, 1670),
  ('monitor', 'BenQ ZOWIE', 'ZOWIE XL2546X+', '{"hz": 280}'::jsonb, 1680),
  ('monitor', 'BenQ ZOWIE', 'ZOWIE XL2566K', '{"hz": 360}'::jsonb, 1690),
  ('monitor', 'BenQ ZOWIE', 'ZOWIE XQ2566X — QHD', '{"hz": 360}'::jsonb, 1700),
  ('monitor', 'BenQ ZOWIE', 'ZOWIE XQ2766X — QHD', '{"hz": 360}'::jsonb, 1710),
  ('monitor', 'BenQ ZOWIE', 'ZOWIE XL2566X+', '{"hz": 400}'::jsonb, 1720),
  ('monitor', 'BenQ ZOWIE', 'ZOWIE XL2586X', '{"hz": 540}'::jsonb, 1730),
  ('monitor', 'BenQ ZOWIE', 'ZOWIE XL2586X+', '{"hz": 600}'::jsonb, 1740),
  ('monitor', 'MSI', 'MSI G274QPX — QHD', '{"hz": 240}'::jsonb, 1750),
  ('monitor', 'MSI', 'MSI MAG 255F X24 — FHD', '{"hz": 240}'::jsonb, 1760),
  ('monitor', 'MSI', 'MSI MAG 272F X24 — FHD', '{"hz": 240}'::jsonb, 1770),
  ('monitor', 'MSI', 'MSI MAG 271QP QD-OLED X24 — QHD', '{"hz": 240}'::jsonb, 1780),
  ('monitor', 'MSI', 'MSI MAG 272QP QD-OLED X24 — QHD', '{"hz": 240}'::jsonb, 1790),
  ('monitor', 'MSI', 'MSI MAG 321UP QD-OLED X24 — 4K', '{"hz": 240}'::jsonb, 1800),
  ('monitor', 'MSI', 'MSI MPG 321URX QD-OLED — 4K', '{"hz": 240}'::jsonb, 1810),
  ('monitor', 'MSI', 'MSI MPG 321URXW QD-OLED — 4K', '{"hz": 240}'::jsonb, 1820),
  ('monitor', 'MSI', 'MSI MPG 322URX QD-OLED — 4K', '{"hz": 240}'::jsonb, 1830),
  ('monitor', 'MSI', 'MSI MPG 272URX QD-OLED — 4K', '{"hz": 240}'::jsonb, 1840),
  ('monitor', 'MSI', 'MSI MPG 491CQPX QD-OLED', '{"hz": 240}'::jsonb, 1850),
  ('monitor', 'MSI', 'MSI Optix MAG251RX — FHD', '{"hz": 240}'::jsonb, 1860),
  ('monitor', 'MSI', 'MSI Optix MAG274QRX — QHD', '{"hz": 240}'::jsonb, 1870),
  ('monitor', 'MSI', 'MSI MAG 274CXF', '{"hz": 280}'::jsonb, 1880),
  ('monitor', 'MSI', 'MSI MAG 276CXF', '{"hz": 280}'::jsonb, 1890),
  ('monitor', 'MSI', 'MSI MAG 271QP QD-OLED X28 — QHD', '{"hz": 280}'::jsonb, 1900),
  ('monitor', 'MSI', 'MSI MAG 272QPW QD-OLED X28 — QHD', '{"hz": 280}'::jsonb, 1910),
  ('monitor', 'MSI', 'MSI MAG 341CQP QD-OLED X28 — UWQHD', '{"hz": 280}'::jsonb, 1920),
  ('monitor', 'MSI', 'MSI MPG 325CQRXF — QHD', '{"hz": 280}'::jsonb, 1930),
  ('monitor', 'MSI', 'MSI MAG 255XF — FHD', '{"hz": 300}'::jsonb, 1940),
  ('monitor', 'MSI', 'MSI MAG 255PXF — FHD', '{"hz": 300}'::jsonb, 1950),
  ('monitor', 'MSI', 'MSI MAG 275QPF X30 — QHD', '{"hz": 300}'::jsonb, 1960),
  ('monitor', 'MSI', 'MSI MAG 274QPF X30MV — QHD', '{"hz": 300}'::jsonb, 1970),
  ('monitor', 'MSI', 'MSI MAG 274QRFW X32 — QHD', '{"hz": 320}'::jsonb, 1980),
  ('monitor', 'MSI', 'MSI MAG 275QF X32 — QHD', '{"hz": 320}'::jsonb, 1990),
  ('monitor', 'MSI', 'MSI MAG 272URDF E16 — 4K 160 / FHD', '{"hz": 320}'::jsonb, 2000),
  ('monitor', 'MSI', 'MSI MAG 322URDF E16 — 4K 160 / FHD', '{"hz": 320}'::jsonb, 2010),
  ('monitor', 'MSI', 'MSI MAG 321CUPDF — 4K 160 / FHD', '{"hz": 320}'::jsonb, 2020),
  ('monitor', 'MSI', 'MSI MAG 274UPDF E16M — 4K 160 / FHD', '{"hz": 320}'::jsonb, 2030),
  ('monitor', 'MSI', 'MSI MPG 274URDFW E16M — 4K 160 / FHD', '{"hz": 320}'::jsonb, 2040),
  ('monitor', 'MSI', 'MSI MAG 271QPX QD-OLED — QHD', '{"hz": 360}'::jsonb, 2050),
  ('monitor', 'MSI', 'MSI MPG 271QRX QD-OLED — QHD', '{"hz": 360}'::jsonb, 2060),
  ('monitor', 'MSI', 'MSI MPG 272QRF X36 — QHD', '{"hz": 360}'::jsonb, 2070),
  ('monitor', 'MSI', 'MSI MPG 341CQR QD-OLED X36 — UWQHD', '{"hz": 360}'::jsonb, 2080),
  ('monitor', 'MSI', 'MSI Oculux NXG253R — FHD', '{"hz": 360}'::jsonb, 2090),
  ('monitor', 'MSI', 'MSI MAG 272QP QD-OLED X50 — QHD', '{"hz": 500}'::jsonb, 2100),
  ('monitor', 'MSI', 'MSI MPG 271QR QD-OLED X50 — QHD', '{"hz": 500}'::jsonb, 2110),
  ('monitor', 'AOC', 'AOC CU34G4Z — UWQHD', '{"hz": 240}'::jsonb, 2120),
  ('monitor', 'AOC', 'AOC C27G2Z — FHD', '{"hz": 240}'::jsonb, 2130),
  ('monitor', 'AOC', 'AOC C32G42ZE', '{"hz": 240}'::jsonb, 2140),
  ('monitor', 'AOC', 'AOC Q27G4ZDR — QHD OLED', '{"hz": 240}'::jsonb, 2150),
  ('monitor', 'AOC', 'AOC Q27G41ZDF — QHD OLED', '{"hz": 240}'::jsonb, 2160),
  ('monitor', 'AOC', 'AOC Q27GAZD — QHD OLED', '{"hz": 240}'::jsonb, 2170),
  ('monitor', 'AOC', 'AOC Q27G41ZE — QHD', '{"hz": 240}'::jsonb, 2180),
  ('monitor', 'AOC', 'AOC AGON PRO AG274QZM — QHD Mini-LED', '{"hz": 240}'::jsonb, 2190),
  ('monitor', 'AOC', 'AOC AGON PRO AG276QZD — QHD OLED', '{"hz": 240}'::jsonb, 2200),
  ('monitor', 'AOC', 'AOC AGON AG251FZ2 — FHD', '{"hz": 240}'::jsonb, 2210),
  ('monitor', 'AOC', 'AOC AGON AG456UCZD — UWQHD OLED', '{"hz": 240}'::jsonb, 2220),
  ('monitor', 'AOC', 'AOC PD27 Porsche Design — QHD', '{"hz": 240}'::jsonb, 2230),
  ('monitor', 'AOC', 'AOC PD49 Porsche Design', '{"hz": 240}'::jsonb, 2240),
  ('monitor', 'AOC', 'AOC CQ27G4ZX — QHD', '{"hz": 300}'::jsonb, 2250),
  ('monitor', 'AOC', 'AOC CQ27G4ZH — QHD', '{"hz": 300}'::jsonb, 2260),
  ('monitor', 'AOC', 'AOC Q27G4SMN — QHD Mini-LED', '{"hz": 320}'::jsonb, 2270),
  ('monitor', 'AOC', 'AOC AGON PRO AG254FG — FHD', '{"hz": 360}'::jsonb, 2280),
  ('monitor', 'AOC', 'AOC AGON PRO AG276QSG2 — QHD', '{"hz": 360}'::jsonb, 2290),
  ('monitor', 'AOC', 'AOC Q27G40SDE — QHD QD-OLED', '{"hz": 360}'::jsonb, 2300),
  ('monitor', 'AOC', 'AOC AGON PRO AGP277QK — QHD', '{"hz": 500}'::jsonb, 2310),
  ('monitor', 'AOC', 'AOC CS24A/P — FHD', '{"hz": 600}'::jsonb, 2320),
  ('mouse', 'Logitech G', 'Logitech G PRO Wireless', '{}'::jsonb, 2330),
  ('mouse', 'Logitech G', 'Logitech G PRO X SUPERLIGHT', '{}'::jsonb, 2340),
  ('mouse', 'Logitech G', 'Logitech G PRO 2 LIGHTSPEED', '{}'::jsonb, 2350),
  ('mouse', 'Logitech G', 'Logitech G PRO X SUPERLIGHT 2', '{}'::jsonb, 2360),
  ('mouse', 'Logitech G', 'Logitech G PRO X SUPERLIGHT 2 SE', '{}'::jsonb, 2370),
  ('mouse', 'Logitech G', 'Logitech G PRO X SUPERLIGHT 2 DEX', '{}'::jsonb, 2380),
  ('mouse', 'Logitech G', 'Logitech G PRO X SUPERLIGHT 2c', '{}'::jsonb, 2390),
  ('mouse', 'Logitech G', 'Logitech G PRO X2 SUPERSTRIKE', '{}'::jsonb, 2400),
  ('mouse', 'Logitech G', 'Logitech G305 LIGHTSPEED', '{}'::jsonb, 2410),
  ('mouse', 'Logitech G', 'Logitech G305 X SUPERLIGHT', '{}'::jsonb, 2420),
  ('mouse', 'Logitech G', 'Logitech G502', '{}'::jsonb, 2430),
  ('mouse', 'Logitech G', 'Logitech G502 LIGHTSPEED', '{}'::jsonb, 2440),
  ('mouse', 'Logitech G', 'Logitech G502 X', '{}'::jsonb, 2450),
  ('mouse', 'Logitech G', 'Logitech G502 X LIGHTSPEED', '{}'::jsonb, 2460),
  ('mouse', 'Logitech G', 'Logitech G502 X PLUS LIGHTSPEED', '{}'::jsonb, 2470),
  ('mouse', 'Logitech G', 'Logitech G203', '{}'::jsonb, 2480),
  ('mouse', 'Logitech G', 'Logitech G403', '{}'::jsonb, 2490),
  ('mouse', 'Logitech G', 'Logitech G703 LIGHTSPEED', '{}'::jsonb, 2500),
  ('mouse', 'Logitech G', 'Logitech G903 LIGHTSPEED', '{}'::jsonb, 2510),
  ('mouse', 'HyperX', 'HyperX Pulsefire Haste 2', '{}'::jsonb, 2520),
  ('mouse', 'HyperX', 'HyperX Pulsefire Haste 2 Wireless', '{}'::jsonb, 2530),
  ('mouse', 'HyperX', 'HyperX Pulsefire Haste 2 Mini Wireless', '{}'::jsonb, 2540),
  ('mouse', 'HyperX', 'HyperX Pulsefire Haste 2 Core Wireless', '{}'::jsonb, 2550),
  ('mouse', 'HyperX', 'HyperX Pulsefire Haste 2 Pro 4K Wireless', '{}'::jsonb, 2560),
  ('mouse', 'HyperX', 'HyperX Pulsefire Haste 2 S Wireless', '{}'::jsonb, 2570),
  ('mouse', 'HyperX', 'HyperX Pulsefire Saga', '{}'::jsonb, 2580),
  ('mouse', 'HyperX', 'HyperX Pulsefire Saga Pro Wireless', '{}'::jsonb, 2590),
  ('mouse', 'HyperX', 'HyperX Pulsefire Fuse Wireless', '{}'::jsonb, 2600),
  ('mouse', 'LAMZU', 'LAMZU MAYA', '{}'::jsonb, 2610),
  ('mouse', 'LAMZU', 'LAMZU MAYA 4K', '{}'::jsonb, 2620),
  ('mouse', 'LAMZU', 'LAMZU MAYA Champion Edition', '{}'::jsonb, 2630),
  ('mouse', 'LAMZU', 'LAMZU MAYA X', '{}'::jsonb, 2640),
  ('mouse', 'LAMZU', 'LAMZU MAYA Doodle', '{}'::jsonb, 2650),
  ('mouse', 'LAMZU', 'LAMZU X AIMLABS MAYA X', '{}'::jsonb, 2660),
  ('mouse', 'LAMZU', 'LAMZU ATLANTIS OG V2 4K', '{}'::jsonb, 2670),
  ('mouse', 'LAMZU', 'LAMZU ATLANTIS OG V2 PRO', '{}'::jsonb, 2680),
  ('mouse', 'LAMZU', 'LAMZU ATLANTIS MINI 4K', '{}'::jsonb, 2690),
  ('mouse', 'LAMZU', 'LAMZU ATLANTIS MINI PRO', '{}'::jsonb, 2700),
  ('mouse', 'LAMZU', 'LAMZU ATLANTIS MINI Champion Edition', '{}'::jsonb, 2710),
  ('mouse', 'LAMZU', 'LAMZU THORN', '{}'::jsonb, 2720),
  ('mouse', 'LAMZU', 'LAMZU THORN 4K', '{}'::jsonb, 2730),
  ('mouse', 'LAMZU', 'LAMZU THORN V2', '{}'::jsonb, 2740),
  ('mouse', 'LAMZU', 'LAMZU X FNATIC THORN 4K', '{}'::jsonb, 2750),
  ('mouse', 'LAMZU', 'LAMZU PARO', '{}'::jsonb, 2760),
  ('mouse', 'LAMZU', 'LAMZU PARO AURORA', '{}'::jsonb, 2770),
  ('mouse', 'LAMZU', 'LAMZU PARO AURORA SE', '{}'::jsonb, 2780),
  ('mouse', 'LAMZU', 'LAMZU X REJECT PARO Special Edition', '{}'::jsonb, 2790),
  ('mouse', 'LAMZU', 'LAMZU INCA', '{}'::jsonb, 2800),
  ('mouse', 'LAMZU', 'LAMZU Tachi Gaming Mouse', '{}'::jsonb, 2810),
  ('mouse', 'Razer', 'Razer Viper V3 Pro', '{}'::jsonb, 2820),
  ('mouse', 'Razer', 'Razer Viper V3 Pro SE', '{}'::jsonb, 2830),
  ('mouse', 'Razer', 'Razer Viper V4 Pro', '{}'::jsonb, 2840),
  ('mouse', 'Razer', 'Razer DeathAdder V3', '{}'::jsonb, 2850),
  ('mouse', 'Razer', 'Razer DeathAdder V3 HyperSpeed', '{}'::jsonb, 2860),
  ('mouse', 'Razer', 'Razer DeathAdder V4 Pro', '{}'::jsonb, 2870),
  ('mouse', 'Razer', 'Razer Basilisk Mobile', '{}'::jsonb, 2880),
  ('mouse', 'Razer', 'Razer Basilisk V3 35K', '{}'::jsonb, 2890),
  ('mouse', 'Razer', 'Razer Basilisk V3 Pro 35K', '{}'::jsonb, 2900),
  ('mouse', 'Razer', 'Razer Cobra', '{}'::jsonb, 2910),
  ('mouse', 'Razer', 'Razer Cobra HyperSpeed', '{}'::jsonb, 2920),
  ('mouse', 'Razer', 'Razer Cobra Pro', '{}'::jsonb, 2930),
  ('mouse', 'Razer', 'Razer Naga V2 HyperSpeed', '{}'::jsonb, 2940),
  ('mouse', 'Razer', 'Razer Naga V3 Pro', '{}'::jsonb, 2950),
  ('mouse', 'Razer', 'Razer Naga Left-Handed Edition', '{}'::jsonb, 2960),
  ('mouse', 'VGN', 'VGN Dragonfly F1 SE', '{}'::jsonb, 2970),
  ('mouse', 'VGN', 'VGN Dragonfly F1 Pro', '{}'::jsonb, 2980),
  ('mouse', 'VGN', 'VGN Dragonfly F1 Pro Max', '{}'::jsonb, 2990),
  ('mouse', 'VGN', 'VGN Dragonfly F1 MOBA', '{}'::jsonb, 3000),
  ('mouse', 'VGN', 'VGN Dragonfly F1 V5', '{}'::jsonb, 3010),
  ('mouse', 'VGN', 'VGN Dragonfly F2', '{}'::jsonb, 3020),
  ('mouse', 'VGN', 'VGN Dragonfly F2 Master', '{}'::jsonb, 3030),
  ('mouse', 'VGN', 'VGN Dragonfly Y2', '{}'::jsonb, 3040),
  ('mouse', 'VGN', 'VGN Dragonfly Y2 Master', '{}'::jsonb, 3050),
  ('mouse', 'VGN', 'VGN Dragonfly Y2 V2', '{}'::jsonb, 3060),
  ('mouse', 'VGN', 'VGN Dragonfly 3', '{}'::jsonb, 3070),
  ('mouse', 'VGN', 'VGN Dragonfly King Magnesium Alloy', '{}'::jsonb, 3080),
  ('mouse', 'AJAZZ', 'AJAZZ AJ139 PRO', '{}'::jsonb, 3090),
  ('mouse', 'AJAZZ', 'AJAZZ AJ139 V2 MC', '{}'::jsonb, 3100),
  ('mouse', 'AJAZZ', 'AJAZZ AJ159', '{}'::jsonb, 3110),
  ('mouse', 'AJAZZ', 'AJAZZ AJ159P', '{}'::jsonb, 3120),
  ('mouse', 'AJAZZ', 'AJAZZ AJ159P MC', '{}'::jsonb, 3130),
  ('mouse', 'AJAZZ', 'AJAZZ AJ159 NL', '{}'::jsonb, 3140),
  ('mouse', 'AJAZZ', 'AJAZZ AJ159 APEX', '{}'::jsonb, 3150),
  ('mouse', 'AJAZZ', 'AJAZZ AJ179', '{}'::jsonb, 3160),
  ('mouse', 'AJAZZ', 'AJAZZ AJ179P', '{}'::jsonb, 3170),
  ('mouse', 'AJAZZ', 'AJAZZ AJ179 PRO', '{}'::jsonb, 3180),
  ('mouse', 'AJAZZ', 'AJAZZ AJ179 APEX', '{}'::jsonb, 3190),
  ('mouse', 'AJAZZ', 'AJAZZ AJ179 V2', '{}'::jsonb, 3200),
  ('mouse', 'AJAZZ', 'AJAZZ AJ199 MAX', '{}'::jsonb, 3210),
  ('mouse', 'AJAZZ', 'AJAZZ AJ199 Carbon Fiber', '{}'::jsonb, 3220),
  ('mouse', 'AJAZZ', 'AJAZZ AJ039', '{}'::jsonb, 3230),
  ('mouse', 'AJAZZ', 'AJAZZ AJ129', '{}'::jsonb, 3240),
  ('mouse', 'AJAZZ', 'AJAZZ AM3', '{}'::jsonb, 3250),
  ('mouse', 'ASUS ROG', 'ROG Harpe Ace Aim Lab Edition', '{}'::jsonb, 3260),
  ('mouse', 'ASUS ROG', 'ROG Harpe Ace Mini', '{}'::jsonb, 3270),
  ('mouse', 'ASUS ROG', 'ROG Harpe Ace Extreme', '{}'::jsonb, 3280),
  ('mouse', 'ASUS ROG', 'ROG Harpe II Ace', '{}'::jsonb, 3290),
  ('mouse', 'ASUS ROG', 'ROG Harpe II Extreme Edition 20', '{}'::jsonb, 3300),
  ('mouse', 'ASUS ROG', 'ROG Keris', '{}'::jsonb, 3310),
  ('mouse', 'ASUS ROG', 'ROG Keris Wireless', '{}'::jsonb, 3320),
  ('mouse', 'ASUS ROG', 'ROG Keris Wireless AimPoint', '{}'::jsonb, 3330),
  ('mouse', 'ASUS ROG', 'ROG Keris II Ace', '{}'::jsonb, 3340),
  ('mouse', 'ASUS ROG', 'ROG Keris II Origin', '{}'::jsonb, 3350),
  ('mouse', 'ASUS ROG', 'ROG Keris II Origin-KJP', '{}'::jsonb, 3360),
  ('mouse', 'ASUS ROG', 'ROG Gladius II', '{}'::jsonb, 3370),
  ('mouse', 'ASUS ROG', 'ROG Gladius II Core', '{}'::jsonb, 3380),
  ('mouse', 'ASUS ROG', 'ROG Gladius II Origin', '{}'::jsonb, 3390),
  ('mouse', 'ASUS ROG', 'ROG Gladius II Wireless', '{}'::jsonb, 3400),
  ('mouse', 'ASUS ROG', 'ROG Gladius III', '{}'::jsonb, 3410),
  ('mouse', 'ASUS ROG', 'ROG Gladius III Wireless', '{}'::jsonb, 3420),
  ('mouse', 'ASUS ROG', 'ROG Gladius III Wireless AimPoint', '{}'::jsonb, 3430),
  ('mouse', 'ASUS ROG', 'ROG Strix Impact II', '{}'::jsonb, 3440),
  ('mouse', 'ASUS ROG', 'ROG Strix Impact II Wireless', '{}'::jsonb, 3450),
  ('mouse', 'ASUS ROG', 'ROG Strix Impact III', '{}'::jsonb, 3460),
  ('mouse', 'ASUS ROG', 'ROG Strix Impact III Wireless', '{}'::jsonb, 3470),
  ('mouse', 'ASUS ROG', 'ROG Chakram', '{}'::jsonb, 3480),
  ('mouse', 'ASUS ROG', 'ROG Chakram Core', '{}'::jsonb, 3490),
  ('mouse', 'ASUS ROG', 'ROG Chakram X', '{}'::jsonb, 3500),
  ('mouse', 'ASUS ROG', 'ROG Chakram X Origin', '{}'::jsonb, 3510),
  ('mouse', 'ASUS ROG', 'ROG Pugio', '{}'::jsonb, 3520),
  ('mouse', 'ASUS ROG', 'ROG Pugio II', '{}'::jsonb, 3530),
  ('mouse', 'ASUS ROG', 'ROG Spatha X', '{}'::jsonb, 3540),
  ('mouse', 'ASUS ROG', 'ROG Strix Carry', '{}'::jsonb, 3550),
  ('mouse', 'ASUS TUF', 'TUF Gaming M3', '{}'::jsonb, 3560),
  ('mouse', 'ASUS TUF', 'TUF Gaming M3 Gen II', '{}'::jsonb, 3570),
  ('mouse', 'ASUS TUF', 'TUF Gaming M4 Air', '{}'::jsonb, 3580),
  ('mouse', 'ASUS TUF', 'TUF Gaming M4 Wireless', '{}'::jsonb, 3590),
  ('mouse', 'ASUS TUF', 'TUF Gaming M5', '{}'::jsonb, 3600),
  ('mouse', 'ASUS TUF', 'TUF Gaming Mini Wireless', '{}'::jsonb, 3610),
  ('mouse', 'ASUS TUF', 'TUF Gaming Mouse x Kimetsu no Yaiba', '{}'::jsonb, 3620),
  ('mouse', 'ZOWIE', 'ZOWIE EC1-DW', '{}'::jsonb, 3630),
  ('mouse', 'ZOWIE', 'ZOWIE EC2-DW', '{}'::jsonb, 3640),
  ('mouse', 'ZOWIE', 'ZOWIE EC3-DW', '{}'::jsonb, 3650),
  ('mouse', 'ZOWIE', 'ZOWIE EC1-DW Glossy', '{}'::jsonb, 3660),
  ('mouse', 'ZOWIE', 'ZOWIE EC2-DW Glossy', '{}'::jsonb, 3670),
  ('mouse', 'ZOWIE', 'ZOWIE EC3-DW Glossy', '{}'::jsonb, 3680),
  ('mouse', 'ZOWIE', 'ZOWIE EC1-CW', '{}'::jsonb, 3690),
  ('mouse', 'ZOWIE', 'ZOWIE EC2-CW', '{}'::jsonb, 3700),
  ('mouse', 'ZOWIE', 'ZOWIE EC3-CW', '{}'::jsonb, 3710),
  ('mouse', 'ZOWIE', 'ZOWIE EC1-C', '{}'::jsonb, 3720),
  ('mouse', 'ZOWIE', 'ZOWIE EC2-C', '{}'::jsonb, 3730),
  ('mouse', 'ZOWIE', 'ZOWIE EC3-C', '{}'::jsonb, 3740),
  ('mouse', 'ZOWIE', 'ZOWIE FK2-DW', '{}'::jsonb, 3750),
  ('mouse', 'ZOWIE', 'ZOWIE FK2-DW Glossy', '{}'::jsonb, 3760),
  ('mouse', 'ZOWIE', 'ZOWIE FK1+-C', '{}'::jsonb, 3770),
  ('mouse', 'ZOWIE', 'ZOWIE FK1-C', '{}'::jsonb, 3780),
  ('mouse', 'ZOWIE', 'ZOWIE FK2-C', '{}'::jsonb, 3790),
  ('mouse', 'ZOWIE', 'ZOWIE ZA13-DW', '{}'::jsonb, 3800),
  ('mouse', 'ZOWIE', 'ZOWIE ZA11-C', '{}'::jsonb, 3810),
  ('mouse', 'ZOWIE', 'ZOWIE ZA12-C', '{}'::jsonb, 3820),
  ('mouse', 'ZOWIE', 'ZOWIE ZA13-C', '{}'::jsonb, 3830),
  ('mouse', 'ZOWIE', 'ZOWIE S2-DW', '{}'::jsonb, 3840),
  ('mouse', 'ZOWIE', 'ZOWIE S2-DW Glossy', '{}'::jsonb, 3850),
  ('mouse', 'ZOWIE', 'ZOWIE S1-C', '{}'::jsonb, 3860),
  ('mouse', 'ZOWIE', 'ZOWIE S2-C', '{}'::jsonb, 3870),
  ('mouse', 'ZOWIE', 'ZOWIE U2', '{}'::jsonb, 3880),
  ('mouse', 'ZOWIE', 'ZOWIE U2-DW', '{}'::jsonb, 3890),
  ('keyboard', 'Royal Kludge', 'Royal Kludge RK61', '{}'::jsonb, 3900),
  ('keyboard', 'Royal Kludge', 'Royal Kludge RK61 Plus', '{}'::jsonb, 3910),
  ('keyboard', 'Royal Kludge', 'Royal Kludge RK61 Pro', '{}'::jsonb, 3920),
  ('keyboard', 'Royal Kludge', 'Royal Kludge RK68', '{}'::jsonb, 3930),
  ('keyboard', 'Royal Kludge', 'Royal Kludge RK68 Plus', '{}'::jsonb, 3940),
  ('keyboard', 'Royal Kludge', 'Royal Kludge RK71', '{}'::jsonb, 3950),
  ('keyboard', 'Royal Kludge', 'Royal Kludge RK84', '{}'::jsonb, 3960),
  ('keyboard', 'Royal Kludge', 'Royal Kludge RK84 Pro', '{}'::jsonb, 3970),
  ('keyboard', 'Royal Kludge', 'Royal Kludge RK87', '{}'::jsonb, 3980),
  ('keyboard', 'Royal Kludge', 'Royal Kludge RK89', '{}'::jsonb, 3990),
  ('keyboard', 'Royal Kludge', 'Royal Kludge RK96', '{}'::jsonb, 4000),
  ('keyboard', 'Royal Kludge', 'Royal Kludge RK98', '{}'::jsonb, 4010),
  ('keyboard', 'Royal Kludge', 'Royal Kludge RK100', '{}'::jsonb, 4020),
  ('keyboard', 'Royal Kludge', 'Royal Kludge RK920', '{}'::jsonb, 4030),
  ('keyboard', 'Royal Kludge', 'Royal Kludge R65 Wired', '{}'::jsonb, 4040),
  ('keyboard', 'Royal Kludge', 'Royal Kludge R65 Wireless', '{}'::jsonb, 4050),
  ('keyboard', 'Royal Kludge', 'Royal Kludge R75 Wired', '{}'::jsonb, 4060),
  ('keyboard', 'Royal Kludge', 'Royal Kludge R75 Wireless', '{}'::jsonb, 4070),
  ('keyboard', 'Royal Kludge', 'Royal Kludge R87 PRO Wired', '{}'::jsonb, 4080),
  ('keyboard', 'Royal Kludge', 'Royal Kludge R87 PRO Wireless', '{}'::jsonb, 4090),
  ('keyboard', 'Royal Kludge', 'Royal Kludge M75', '{}'::jsonb, 4100),
  ('keyboard', 'Royal Kludge', 'Royal Kludge M87', '{}'::jsonb, 4110),
  ('keyboard', 'Royal Kludge', 'Royal Kludge S85', '{}'::jsonb, 4120),
  ('keyboard', 'Royal Kludge', 'Royal Kludge S98', '{}'::jsonb, 4130),
  ('keyboard', 'Royal Kludge', 'Royal Kludge F68', '{}'::jsonb, 4140),
  ('keyboard', 'Royal Kludge', 'Royal Kludge F99', '{}'::jsonb, 4150),
  ('keyboard', 'Royal Kludge', 'Royal Kludge F99 AI', '{}'::jsonb, 4160),
  ('keyboard', 'Royal Kludge', 'Royal Kludge L75', '{}'::jsonb, 4170),
  ('keyboard', 'Royal Kludge', 'Royal Kludge L98', '{}'::jsonb, 4180),
  ('keyboard', 'Royal Kludge', 'Royal Kludge C68 HE', '{}'::jsonb, 4190),
  ('keyboard', 'Royal Kludge', 'Royal Kludge C84 HE', '{}'::jsonb, 4200),
  ('keyboard', 'Royal Kludge', 'Royal Kludge C87 HE', '{}'::jsonb, 4210),
  ('keyboard', 'Royal Kludge', 'Royal Kludge C96 HE', '{}'::jsonb, 4220),
  ('keyboard', 'Royal Kludge', 'Royal Kludge C98 HE', '{}'::jsonb, 4230),
  ('keyboard', 'Royal Kludge', 'Royal Kludge N80', '{}'::jsonb, 4240),
  ('keyboard', 'HyperX', 'HyperX Origins 2 65', '{}'::jsonb, 4250),
  ('keyboard', 'HyperX', 'HyperX Origins 2 65 Pro Magnetic', '{}'::jsonb, 4260),
  ('keyboard', 'HyperX', 'HyperX Origins 2 1800', '{}'::jsonb, 4270),
  ('keyboard', 'HyperX', 'HyperX Alloy Rise', '{}'::jsonb, 4280),
  ('keyboard', 'HyperX', 'HyperX Alloy Rise 75', '{}'::jsonb, 4290),
  ('keyboard', 'HyperX', 'HyperX Alloy Rise 75 Wireless', '{}'::jsonb, 4300),
  ('keyboard', 'HyperX', 'HyperX Alloy Origins', '{}'::jsonb, 4310),
  ('keyboard', 'HyperX', 'HyperX Alloy Origins PBT', '{}'::jsonb, 4320),
  ('keyboard', 'HyperX', 'HyperX Alloy Origins Core', '{}'::jsonb, 4330),
  ('keyboard', 'HyperX', 'HyperX Alloy Origins Core PBT', '{}'::jsonb, 4340),
  ('keyboard', 'HyperX', 'HyperX Alloy Origins 60', '{}'::jsonb, 4350),
  ('keyboard', 'HyperX', 'HyperX Alloy Origins 65', '{}'::jsonb, 4360),
  ('keyboard', 'HyperX', 'HyperX Alloy Elite', '{}'::jsonb, 4370),
  ('keyboard', 'HyperX', 'HyperX Alloy Elite 2', '{}'::jsonb, 4380),
  ('keyboard', 'HyperX', 'HyperX Alloy Core RGB', '{}'::jsonb, 4390),
  ('keyboard', 'HyperX', 'HyperX Alloy MKW100', '{}'::jsonb, 4400),
  ('keyboard', 'HyperX', 'HyperX Eve 1800', '{}'::jsonb, 4410),
  ('keyboard', 'Logitech G', 'Logitech G PRO', '{}'::jsonb, 4420),
  ('keyboard', 'Logitech G', 'Logitech G PRO X', '{}'::jsonb, 4430),
  ('keyboard', 'Logitech G', 'Logitech G PRO X TKL', '{}'::jsonb, 4440),
  ('keyboard', 'Logitech G', 'Logitech G PRO X TKL LIGHTSPEED', '{}'::jsonb, 4450),
  ('keyboard', 'Logitech G', 'Logitech G PRO X TKL RAPID', '{}'::jsonb, 4460),
  ('keyboard', 'Logitech G', 'Logitech G PRO X 60', '{}'::jsonb, 4470),
  ('keyboard', 'Logitech G', 'Logitech G915', '{}'::jsonb, 4480),
  ('keyboard', 'Logitech G', 'Logitech G915 TKL', '{}'::jsonb, 4490),
  ('keyboard', 'Logitech G', 'Logitech G915 X', '{}'::jsonb, 4500),
  ('keyboard', 'Logitech G', 'Logitech G915 X LIGHTSPEED', '{}'::jsonb, 4510),
  ('keyboard', 'Logitech G', 'Logitech G915 X LIGHTSPEED TKL', '{}'::jsonb, 4520),
  ('keyboard', 'Logitech G', 'Logitech G515 TKL', '{}'::jsonb, 4530),
  ('keyboard', 'Logitech G', 'Logitech G515 LIGHTSPEED TKL', '{}'::jsonb, 4540),
  ('keyboard', 'Logitech G', 'Logitech G515 RAPID TKL', '{}'::jsonb, 4550),
  ('keyboard', 'Logitech G', 'Logitech G512', '{}'::jsonb, 4560),
  ('keyboard', 'Logitech G', 'Logitech G512 X 75', '{}'::jsonb, 4570),
  ('keyboard', 'Logitech G', 'Logitech G512 X 98', '{}'::jsonb, 4580),
  ('keyboard', 'Logitech G', 'Logitech G413', '{}'::jsonb, 4590),
  ('keyboard', 'Logitech G', 'Logitech G413 SE', '{}'::jsonb, 4600),
  ('keyboard', 'Logitech G', 'Logitech G413 TKL SE', '{}'::jsonb, 4610),
  ('keyboard', 'Logitech G', 'Logitech G713', '{}'::jsonb, 4620),
  ('keyboard', 'Logitech G', 'Logitech G715', '{}'::jsonb, 4630),
  ('keyboard', 'Logitech G', 'Logitech G213 Prodigy', '{}'::jsonb, 4640),
  ('keyboard', 'Logitech G', 'Logitech G316 X 98', '{}'::jsonb, 4650),
  ('keyboard', 'Logitech G', 'Logitech G513', '{}'::jsonb, 4660),
  ('keyboard', 'Logitech G', 'Logitech G613', '{}'::jsonb, 4670),
  ('keyboard', 'Logitech G', 'Logitech G815', '{}'::jsonb, 4680),
  ('keyboard', 'Logitech G', 'Logitech G910 Orion Spectrum', '{}'::jsonb, 4690),
  ('keyboard', 'Dark Project', 'Dark Project ALU68A Relic', '{}'::jsonb, 4700),
  ('keyboard', 'Dark Project', 'Dark Project ALU81A Terra Nova', '{}'::jsonb, 4710),
  ('keyboard', 'Dark Project', 'Dark Project ALU81A Terra Nostra', '{}'::jsonb, 4720),
  ('keyboard', 'Dark Project', 'Dark Project ALU87A Onionite', '{}'::jsonb, 4730),
  ('keyboard', 'Dark Project', 'Dark Project ALU87A Onionite V2', '{}'::jsonb, 4740),
  ('keyboard', 'Dark Project', 'Dark Project ALU87A Midnight', '{}'::jsonb, 4750),
  ('keyboard', 'Dark Project', 'Dark Project ALU87A Violet', '{}'::jsonb, 4760),
  ('keyboard', 'Dark Project', 'Dark Project ALU87B Bushido', '{}'::jsonb, 4770),
  ('keyboard', 'Dark Project', 'Dark Project ALU87B Celestial', '{}'::jsonb, 4780),
  ('keyboard', 'Dark Project', 'Dark Project ALU87B Delta', '{}'::jsonb, 4790),
  ('keyboard', 'Dark Project', 'Dark Project ALU87B Gamma', '{}'::jsonb, 4800),
  ('keyboard', 'Dark Project', 'Dark Project 87 Fuji', '{}'::jsonb, 4810),
  ('keyboard', 'Dark Project', 'Dark Project 87 Fuji V2', '{}'::jsonb, 4820),
  ('keyboard', 'Dark Project', 'Dark Project KD83A', '{}'::jsonb, 4830),
  ('keyboard', 'Dark Project', 'Dark Project KD87A', '{}'::jsonb, 4840),
  ('keyboard', 'Dark Project', 'Dark Project KD87A Skeleton', '{}'::jsonb, 4850),
  ('keyboard', 'Dark Project', 'Dark Project KD87A Gateron', '{}'::jsonb, 4860),
  ('keyboard', 'Dark Project', 'Dark Project KD104A', '{}'::jsonb, 4870),
  ('keyboard', 'Dark Project', 'Dark Project KD104A ABS', '{}'::jsonb, 4880),
  ('keyboard', 'Dark Project', 'Dark Project DPP 87', '{}'::jsonb, 4890),
  ('keyboard', 'AJAZZ', 'AJAZZ AK820', '{}'::jsonb, 4900),
  ('keyboard', 'AJAZZ', 'AJAZZ AK820 PRO', '{}'::jsonb, 4910),
  ('keyboard', 'AJAZZ', 'AJAZZ AK820 MAX', '{}'::jsonb, 4920),
  ('keyboard', 'AJAZZ', 'AJAZZ AK820 MAX PLUS', '{}'::jsonb, 4930),
  ('keyboard', 'AJAZZ', 'AJAZZ AK820 MAX Ultra HE', '{}'::jsonb, 4940),
  ('keyboard', 'AJAZZ', 'AJAZZ AK870', '{}'::jsonb, 4950),
  ('keyboard', 'AJAZZ', 'AJAZZ AK870 Plus', '{}'::jsonb, 4960),
  ('keyboard', 'AJAZZ', 'AJAZZ AK680', '{}'::jsonb, 4970),
  ('keyboard', 'AJAZZ', 'AJAZZ AK680 MAX HE', '{}'::jsonb, 4980),
  ('keyboard', 'AJAZZ', 'AJAZZ AK980', '{}'::jsonb, 4990),
  ('keyboard', 'AJAZZ', 'AJAZZ AK35I', '{}'::jsonb, 5000),
  ('keyboard', 'AJAZZ', 'AJAZZ AK35I V2', '{}'::jsonb, 5010),
  ('keyboard', 'AJAZZ', 'AJAZZ AK35I V3', '{}'::jsonb, 5020),
  ('keyboard', 'AJAZZ', 'AJAZZ AK35I V3 MAX', '{}'::jsonb, 5030),
  ('keyboard', 'AJAZZ', 'AJAZZ AK35I V4', '{}'::jsonb, 5040),
  ('keyboard', 'AJAZZ', 'AJAZZ AK33', '{}'::jsonb, 5050),
  ('keyboard', 'AJAZZ', 'AJAZZ AK40', '{}'::jsonb, 5060),
  ('keyboard', 'AJAZZ', 'AJAZZ AK510', '{}'::jsonb, 5070),
  ('keyboard', 'AJAZZ', 'AJAZZ AK515', '{}'::jsonb, 5080),
  ('keyboard', 'AJAZZ', 'AJAZZ AK690', '{}'::jsonb, 5090),
  ('keyboard', 'AJAZZ', 'AJAZZ AK692', '{}'::jsonb, 5100),
  ('keyboard', 'AJAZZ', 'AJAZZ AK832', '{}'::jsonb, 5110),
  ('keyboard', 'AJAZZ', 'AJAZZ AK873', '{}'::jsonb, 5120),
  ('keyboard', 'AJAZZ', 'AJAZZ AK966', '{}'::jsonb, 5130),
  ('keyboard', 'AJAZZ', 'AJAZZ AK992', '{}'::jsonb, 5140),
  ('keyboard', 'AJAZZ', 'AJAZZ AKS068', '{}'::jsonb, 5150),
  ('keyboard', 'AJAZZ', 'AJAZZ AKS075', '{}'::jsonb, 5160),
  ('keyboard', 'AJAZZ', 'AJAZZ AC067', '{}'::jsonb, 5170),
  ('keyboard', 'AJAZZ', 'AJAZZ ALUX68 HE', '{}'::jsonb, 5180),
  ('keyboard', 'AJAZZ', 'AJAZZ NK104', '{}'::jsonb, 5190),
  ('keyboard', 'Razer', 'Razer Huntsman V3 HE Magnetic', '{}'::jsonb, 5200),
  ('keyboard', 'Razer', 'Razer Huntsman V3 HE Magnetic Mini', '{}'::jsonb, 5210),
  ('keyboard', 'Razer', 'Razer Huntsman V3 HE Magnetic Tenkeyless', '{}'::jsonb, 5220),
  ('keyboard', 'Razer', 'Razer Huntsman V3 Pro', '{}'::jsonb, 5230),
  ('keyboard', 'Razer', 'Razer Huntsman V3 Pro 8KHz', '{}'::jsonb, 5240),
  ('keyboard', 'Razer', 'Razer Huntsman V3 Pro Tenkeyless', '{}'::jsonb, 5250),
  ('keyboard', 'Razer', 'Razer Huntsman V3 Pro Tenkeyless 8KHz', '{}'::jsonb, 5260),
  ('keyboard', 'Razer', 'Razer Huntsman V3 Pro Mini', '{}'::jsonb, 5270),
  ('keyboard', 'Razer', 'Razer Huntsman V3 Tenkeyless', '{}'::jsonb, 5280),
  ('keyboard', 'Razer', 'Razer Huntsman V3 X Tenkeyless', '{}'::jsonb, 5290),
  ('keyboard', 'Razer', 'Razer Huntsman Signature Edition', '{}'::jsonb, 5300),
  ('keyboard', 'Razer', 'Razer Huntsman V2', '{}'::jsonb, 5310),
  ('keyboard', 'Razer', 'Razer Huntsman V2 Tenkeyless', '{}'::jsonb, 5320),
  ('keyboard', 'Razer', 'Razer Huntsman Mini', '{}'::jsonb, 5330),
  ('keyboard', 'Razer', 'Razer Huntsman Mini Analog', '{}'::jsonb, 5340),
  ('keyboard', 'Razer', 'Razer Huntsman V2 Analog', '{}'::jsonb, 5350),
  ('keyboard', 'Razer', 'Razer Huntsman Tournament Edition', '{}'::jsonb, 5360),
  ('keyboard', 'Razer', 'Razer BlackWidow V4', '{}'::jsonb, 5370),
  ('keyboard', 'Razer', 'Razer BlackWidow V4 X', '{}'::jsonb, 5380),
  ('keyboard', 'Razer', 'Razer BlackWidow V4 Pro', '{}'::jsonb, 5390),
  ('keyboard', 'Razer', 'Razer BlackWidow V4 75%', '{}'::jsonb, 5400),
  ('keyboard', 'Razer', 'Razer BlackWidow V4 75% Pro', '{}'::jsonb, 5410),
  ('keyboard', 'Razer', 'Razer BlackWidow V4 Low-profile HyperSpeed', '{}'::jsonb, 5420),
  ('keyboard', 'Razer', 'Razer BlackWidow V4 Low-profile Tenkeyless HyperSpeed', '{}'::jsonb, 5430),
  ('keyboard', 'Razer', 'Razer BlackWidow V3', '{}'::jsonb, 5440),
  ('keyboard', 'Razer', 'Razer BlackWidow V3 Pro', '{}'::jsonb, 5450),
  ('keyboard', 'Razer', 'Razer BlackWidow V3 Tenkeyless', '{}'::jsonb, 5460),
  ('keyboard', 'Razer', 'Razer BlackWidow V3 Mini HyperSpeed', '{}'::jsonb, 5470),
  ('keyboard', 'Razer', 'Razer DeathStalker V2', '{}'::jsonb, 5480),
  ('keyboard', 'Razer', 'Razer DeathStalker V2 Pro', '{}'::jsonb, 5490),
  ('keyboard', 'Razer', 'Razer DeathStalker V2 Pro Tenkeyless', '{}'::jsonb, 5500),
  ('keyboard', 'Razer', 'Razer Ornata V3', '{}'::jsonb, 5510),
  ('keyboard', 'Razer', 'Razer Ornata V3 Tenkeyless', '{}'::jsonb, 5520),
  ('keyboard', 'Razer', 'Razer Ornata V3 X', '{}'::jsonb, 5530),
  ('keyboard', 'ASUS ROG', 'ROG Azoth', '{}'::jsonb, 5540),
  ('keyboard', 'ASUS ROG', 'ROG Azoth X', '{}'::jsonb, 5550),
  ('keyboard', 'ASUS ROG', 'ROG Azoth Extreme', '{}'::jsonb, 5560),
  ('keyboard', 'ASUS ROG', 'ROG Azoth Extreme Edition 20', '{}'::jsonb, 5570),
  ('keyboard', 'ASUS ROG', 'ROG Azoth 96 HE', '{}'::jsonb, 5580),
  ('keyboard', 'ASUS ROG', 'ROG Azoth 96 HE Lite', '{}'::jsonb, 5590),
  ('keyboard', 'ASUS ROG', 'ROG Falchion', '{}'::jsonb, 5600),
  ('keyboard', 'ASUS ROG', 'ROG Falchion NX', '{}'::jsonb, 5610),
  ('keyboard', 'ASUS ROG', 'ROG Falchion RX Low Profile', '{}'::jsonb, 5620),
  ('keyboard', 'ASUS ROG', 'ROG Falchion Ace', '{}'::jsonb, 5630),
  ('keyboard', 'ASUS ROG', 'ROG Falchion Ace HFX', '{}'::jsonb, 5640),
  ('keyboard', 'ASUS ROG', 'ROG Falchion Ace HFX ZywOo Edition', '{}'::jsonb, 5650),
  ('keyboard', 'ASUS ROG', 'ROG Falchion Ace 75 HE', '{}'::jsonb, 5660),
  ('keyboard', 'ASUS ROG', 'ROG Strix Scope', '{}'::jsonb, 5670),
  ('keyboard', 'ASUS ROG', 'ROG Strix Scope Deluxe', '{}'::jsonb, 5680),
  ('keyboard', 'ASUS ROG', 'ROG Strix Scope TKL', '{}'::jsonb, 5690),
  ('keyboard', 'ASUS ROG', 'ROG Strix Scope TKL Deluxe', '{}'::jsonb, 5700),
  ('keyboard', 'ASUS ROG', 'ROG Strix Scope NX TKL', '{}'::jsonb, 5710),
  ('keyboard', 'ASUS ROG', 'ROG Strix Scope RX', '{}'::jsonb, 5720),
  ('keyboard', 'ASUS ROG', 'ROG Strix Scope RX TKL Wireless Deluxe', '{}'::jsonb, 5730),
  ('keyboard', 'ASUS ROG', 'ROG Strix Scope II', '{}'::jsonb, 5740),
  ('keyboard', 'ASUS ROG', 'ROG Strix Scope II RX', '{}'::jsonb, 5750),
  ('keyboard', 'ASUS ROG', 'ROG Strix Scope II 96 Wireless', '{}'::jsonb, 5760),
  ('keyboard', 'ASUS ROG', 'ROG Strix Scope II 96 RX Wireless', '{}'::jsonb, 5770),
  ('keyboard', 'ASUS ROG', 'ROG Strix Scope II X', '{}'::jsonb, 5780),
  ('keyboard', 'ASUS ROG', 'ROG Strix Flare', '{}'::jsonb, 5790),
  ('keyboard', 'ASUS ROG', 'ROG Strix Flare II', '{}'::jsonb, 5800),
  ('keyboard', 'ASUS ROG', 'ROG Strix Flare II Animate', '{}'::jsonb, 5810),
  ('keyboard', 'ASUS ROG', 'ROG Claymore', '{}'::jsonb, 5820),
  ('keyboard', 'ASUS ROG', 'ROG Claymore II', '{}'::jsonb, 5830),
  ('keyboard', 'ASUS ROG', 'ROG Falcata', '{}'::jsonb, 5840),
  ('keyboard', 'ASUS ROG', 'ROG Strix Morph 96 Wireless', '{}'::jsonb, 5850),
  ('keyboard', 'ASUS TUF', 'TUF Gaming K1', '{}'::jsonb, 5860),
  ('keyboard', 'ASUS TUF', 'TUF Gaming K3', '{}'::jsonb, 5870),
  ('keyboard', 'ASUS TUF', 'TUF Gaming K3 Gen II', '{}'::jsonb, 5880),
  ('keyboard', 'ASUS TUF', 'TUF Gaming K5', '{}'::jsonb, 5890),
  ('keyboard', 'ASUS TUF', 'TUF Gaming K7', '{}'::jsonb, 5900),
  ('headset', 'HyperX', 'HyperX Cloud III', '{}'::jsonb, 5910),
  ('headset', 'HyperX', 'HyperX Cloud III Wireless', '{}'::jsonb, 5920),
  ('headset', 'HyperX', 'HyperX Cloud III S Wireless', '{}'::jsonb, 5930),
  ('headset', 'HyperX', 'HyperX Cloud II', '{}'::jsonb, 5940),
  ('headset', 'HyperX', 'HyperX Cloud II Wireless', '{}'::jsonb, 5950),
  ('headset', 'HyperX', 'HyperX Cloud II Core Wireless', '{}'::jsonb, 5960),
  ('headset', 'HyperX', 'HyperX Cloud Alpha', '{}'::jsonb, 5970),
  ('headset', 'HyperX', 'HyperX Cloud Alpha Wireless', '{}'::jsonb, 5980),
  ('headset', 'HyperX', 'HyperX Cloud Alpha 2 Wireless', '{}'::jsonb, 5990),
  ('headset', 'HyperX', 'HyperX Cloud Alpha S', '{}'::jsonb, 6000),
  ('headset', 'HyperX', 'HyperX Cloud Alpha S Blackout Edition', '{}'::jsonb, 6010),
  ('headset', 'HyperX', 'HyperX Cloud Flight', '{}'::jsonb, 6020),
  ('headset', 'HyperX', 'HyperX Cloud Flight S', '{}'::jsonb, 6030),
  ('headset', 'HyperX', 'HyperX Cloud Flight 2 Wireless', '{}'::jsonb, 6040),
  ('headset', 'HyperX', 'HyperX Cloud Stinger 3 Wired', '{}'::jsonb, 6050),
  ('headset', 'HyperX', 'HyperX Cloud Stinger 3 Wireless', '{}'::jsonb, 6060),
  ('headset', 'HyperX', 'HyperX Cloud Stinger 2', '{}'::jsonb, 6070),
  ('headset', 'HyperX', 'HyperX Cloud Stinger 2 Wireless', '{}'::jsonb, 6080),
  ('headset', 'HyperX', 'HyperX Cloud Stinger 2 Core', '{}'::jsonb, 6090),
  ('headset', 'HyperX', 'HyperX Cloud Jet Wireless', '{}'::jsonb, 6100),
  ('headset', 'HyperX', 'HyperX Cloud MIX 2', '{}'::jsonb, 6110),
  ('headset', 'HyperX', 'HyperX Cloud Mini Wired', '{}'::jsonb, 6120),
  ('headset', 'HyperX', 'HyperX Cloud Mini Wireless', '{}'::jsonb, 6130),
  ('headset', 'HyperX', 'HyperX Cloud Core', '{}'::jsonb, 6140),
  ('headset', 'HyperX', 'HyperX Cloud Core Wireless', '{}'::jsonb, 6150),
  ('headset', 'HyperX', 'HyperX Cloud Revolver', '{}'::jsonb, 6160),
  ('headset', 'HyperX', 'HyperX Cloud Revolver S', '{}'::jsonb, 6170),
  ('headset', 'HyperX', 'HyperX Cloud Orbit', '{}'::jsonb, 6180),
  ('headset', 'HyperX', 'HyperX Cloud Orbit S', '{}'::jsonb, 6190),
  ('headset', 'HyperX', 'HyperX Cloud MIX', '{}'::jsonb, 6200),
  ('headset', 'HyperX', 'HyperX Cloud Stinger', '{}'::jsonb, 6210),
  ('headset', 'HyperX', 'HyperX Cloud Stinger Core', '{}'::jsonb, 6220),
  ('headset', 'HyperX', 'HyperX Cloud Stinger S', '{}'::jsonb, 6230),
  ('headset', 'Razer', 'Razer BlackShark V3 Pro', '{}'::jsonb, 6240),
  ('headset', 'Razer', 'Razer BlackShark V3', '{}'::jsonb, 6250),
  ('headset', 'Razer', 'Razer BlackShark V3 X HyperSpeed', '{}'::jsonb, 6260),
  ('headset', 'Razer', 'Razer BlackShark V2 Pro', '{}'::jsonb, 6270),
  ('headset', 'Razer', 'Razer BlackShark V2', '{}'::jsonb, 6280),
  ('headset', 'Razer', 'Razer BlackShark V2 X', '{}'::jsonb, 6290),
  ('headset', 'Razer', 'Razer Kraken V4 Pro', '{}'::jsonb, 6300),
  ('headset', 'Razer', 'Razer Kraken V4', '{}'::jsonb, 6310),
  ('headset', 'Razer', 'Razer Kraken V4 X', '{}'::jsonb, 6320),
  ('headset', 'Razer', 'Razer Kraken Kitty V3 Pro', '{}'::jsonb, 6330),
  ('headset', 'Razer', 'Razer Kraken Kitty V3 X', '{}'::jsonb, 6340),
  ('headset', 'Razer', 'Razer Kraken Kitty V2', '{}'::jsonb, 6350),
  ('headset', 'Razer', 'Razer Kraken Kitty V2 Pro', '{}'::jsonb, 6360),
  ('headset', 'Razer', 'Razer Kraken V3', '{}'::jsonb, 6370),
  ('headset', 'Razer', 'Razer Kraken V3 Pro', '{}'::jsonb, 6380),
  ('headset', 'Razer', 'Razer Kraken V3 HyperSense', '{}'::jsonb, 6390),
  ('headset', 'Razer', 'Razer Kraken V3 X', '{}'::jsonb, 6400),
  ('headset', 'Razer', 'Razer Kraken', '{}'::jsonb, 6410),
  ('headset', 'Razer', 'Razer Kraken Ultimate', '{}'::jsonb, 6420),
  ('headset', 'Razer', 'Razer Kraken Tournament Edition', '{}'::jsonb, 6430),
  ('headset', 'Razer', 'Razer Kraken X', '{}'::jsonb, 6440),
  ('headset', 'Razer', 'Razer Barracuda Pro', '{}'::jsonb, 6450),
  ('headset', 'Razer', 'Razer Barracuda', '{}'::jsonb, 6460),
  ('headset', 'Razer', 'Razer Barracuda X', '{}'::jsonb, 6470),
  ('headset', 'Razer', 'Razer Barracuda X Chroma', '{}'::jsonb, 6480),
  ('headset', 'Razer', 'Razer Kaira Pro HyperSpeed', '{}'::jsonb, 6490),
  ('headset', 'Razer', 'Razer Kaira HyperSpeed', '{}'::jsonb, 6500),
  ('headset', 'Razer', 'Razer Nari Ultimate', '{}'::jsonb, 6510),
  ('headset', 'Razer', 'Razer Hammerhead V3', '{}'::jsonb, 6520),
  ('headset', 'Razer', 'Razer Hammerhead V3 HyperSpeed', '{}'::jsonb, 6530),
  ('headset', 'Logitech G', 'Logitech G325 LIGHTSPEED', '{}'::jsonb, 6540),
  ('headset', 'Logitech G', 'Logitech G321 LIGHTSPEED', '{}'::jsonb, 6550),
  ('headset', 'Logitech G', 'Logitech G522 LIGHTSPEED', '{}'::jsonb, 6560),
  ('headset', 'Logitech G', 'Logitech G PRO Gaming Headset', '{}'::jsonb, 6570),
  ('headset', 'Logitech G', 'Logitech G PRO X Wired', '{}'::jsonb, 6580),
  ('headset', 'Logitech G', 'Logitech G PRO X Wireless', '{}'::jsonb, 6590),
  ('headset', 'Logitech G', 'Logitech G PRO X 2 LIGHTSPEED', '{}'::jsonb, 6600),
  ('headset', 'Logitech G', 'Logitech G733 LIGHTSPEED', '{}'::jsonb, 6610),
  ('headset', 'Logitech G', 'Logitech G735 LIGHTSPEED', '{}'::jsonb, 6620),
  ('headset', 'Logitech G', 'Logitech G435', '{}'::jsonb, 6630),
  ('headset', 'Logitech G', 'Logitech G335', '{}'::jsonb, 6640),
  ('headset', 'Logitech G', 'Logitech G535 LIGHTSPEED', '{}'::jsonb, 6650),
  ('headset', 'Logitech G', 'Logitech G432', '{}'::jsonb, 6660),
  ('headset', 'Logitech G', 'Logitech G433', '{}'::jsonb, 6670),
  ('headset', 'Logitech G', 'Logitech G935', '{}'::jsonb, 6680),
  ('headset', 'Logitech G', 'Logitech G533', '{}'::jsonb, 6690),
  ('headset', 'ASTRO', 'ASTRO A50 X LIGHTSPEED', '{}'::jsonb, 6700),
  ('headset', 'ASTRO', 'ASTRO A50 Gen 5', '{}'::jsonb, 6710),
  ('headset', 'ASTRO', 'ASTRO A50 Gen 4', '{}'::jsonb, 6720),
  ('headset', 'ASTRO', 'ASTRO A20 X LIGHTSPEED', '{}'::jsonb, 6730),
  ('headset', 'ASTRO', 'ASTRO A30 LIGHTSPEED', '{}'::jsonb, 6740),
  ('headset', 'ASTRO', 'ASTRO A40 TR', '{}'::jsonb, 6750),
  ('headset', 'ASTRO', 'ASTRO A40 TR + MixAmp Pro TR', '{}'::jsonb, 6760),
  ('headset', 'ASTRO', 'ASTRO A10', '{}'::jsonb, 6770),
  ('headset', 'ASTRO', 'ASTRO A10 Gen 2', '{}'::jsonb, 6780),
  ('chair', 'AndaSeat', 'AndaSeat Kaiser', '{}'::jsonb, 6790),
  ('chair', 'AndaSeat', 'AndaSeat Kaiser 2', '{}'::jsonb, 6800),
  ('chair', 'AndaSeat', 'AndaSeat Kaiser 3', '{}'::jsonb, 6810),
  ('chair', 'AndaSeat', 'AndaSeat Kaiser 3 Pro', '{}'::jsonb, 6820),
  ('chair', 'AndaSeat', 'AndaSeat Kaiser 3E', '{}'::jsonb, 6830),
  ('chair', 'AndaSeat', 'AndaSeat Kaiser Frontier', '{}'::jsonb, 6840),
  ('chair', 'AndaSeat', 'AndaSeat Kaiser 4', '{}'::jsonb, 6850),
  ('chair', 'AndaSeat', 'AndaSeat New Kaiser 4', '{}'::jsonb, 6860),
  ('chair', 'AndaSeat', 'AndaSeat Phantom 3', '{}'::jsonb, 6870),
  ('chair', 'AndaSeat', 'AndaSeat Phantom 4', '{}'::jsonb, 6880),
  ('chair', 'AndaSeat', 'AndaSeat Phantom 4 Pro', '{}'::jsonb, 6890),
  ('chair', 'AndaSeat', 'AndaSeat X-Air', '{}'::jsonb, 6900),
  ('chair', 'AndaSeat', 'AndaSeat X-Air Pro', '{}'::jsonb, 6910),
  ('chair', 'AndaSeat', 'AndaSeat Novis', '{}'::jsonb, 6920),
  ('chair', 'AndaSeat', 'AndaSeat T-Pro', '{}'::jsonb, 6930),
  ('chair', 'AndaSeat', 'AndaSeat T-Pro 2', '{}'::jsonb, 6940),
  ('chair', 'AndaSeat', 'AndaSeat Jungle', '{}'::jsonb, 6950),
  ('chair', 'AndaSeat', 'AndaSeat Jungle 2', '{}'::jsonb, 6960),
  ('chair', 'AndaSeat', 'AndaSeat Dark Demon', '{}'::jsonb, 6970),
  ('chair', 'AndaSeat', 'AndaSeat T-Compact', '{}'::jsonb, 6980),
  ('chair', 'DXRacer', 'DXRacer MARTIAN', '{}'::jsonb, 6990),
  ('chair', 'DXRacer', 'DXRacer MARTIAN Pro', '{}'::jsonb, 7000),
  ('chair', 'DXRacer', 'DXRacer FORMULA', '{}'::jsonb, 7010),
  ('chair', 'DXRacer', 'DXRacer RACING', '{}'::jsonb, 7020),
  ('chair', 'DXRacer', 'DXRacer DRIFTING', '{}'::jsonb, 7030),
  ('chair', 'DXRacer', 'DXRacer BLADE', '{}'::jsonb, 7040),
  ('chair', 'DXRacer', 'DXRacer CRAFT', '{}'::jsonb, 7050),
  ('chair', 'DXRacer', 'DXRacer MASTER', '{}'::jsonb, 7060),
  ('chair', 'DXRacer', 'DXRacer TANK', '{}'::jsonb, 7070),
  ('chair', 'DXRacer', 'DXRacer AIR', '{}'::jsonb, 7080),
  ('chair', 'DXRacer', 'DXRacer PRINCE', '{}'::jsonb, 7090),
  ('chair', 'DXRacer', 'DXRacer KING', '{}'::jsonb, 7100),
  ('chair', 'DXRacer', 'DXRacer VALKYRIE', '{}'::jsonb, 7110),
  ('chair', 'DXRacer', 'DXRacer SENTINEL', '{}'::jsonb, 7120),
  ('chair', 'DXRacer', 'DXRacer BOSS', '{}'::jsonb, 7130),
  ('chair', 'DXRacer', 'DXRacer CLASSIC', '{}'::jsonb, 7140),
  ('chair', 'DXRacer', 'DXRacer WORK', '{}'::jsonb, 7150),
  ('chair', 'DXRacer', 'DXRacer ELITE', '{}'::jsonb, 7160),
  ('chair', 'DXRacer', 'DXRacer IRON', '{}'::jsonb, 7170),
  ('chair', 'Razer', 'Razer Iskur', '{}'::jsonb, 7180),
  ('chair', 'Razer', 'Razer Iskur Fabric', '{}'::jsonb, 7190),
  ('chair', 'Razer', 'Razer Iskur XL', '{}'::jsonb, 7200),
  ('chair', 'Razer', 'Razer Iskur X', '{}'::jsonb, 7210),
  ('chair', 'Razer', 'Razer Iskur X XL', '{}'::jsonb, 7220),
  ('chair', 'Razer', 'Razer Iskur V2', '{}'::jsonb, 7230),
  ('chair', 'Razer', 'Razer Iskur V2 X', '{}'::jsonb, 7240),
  ('chair', 'Razer', 'Razer Iskur V2 NewGen', '{}'::jsonb, 7250),
  ('chair', 'Razer', 'Razer Iskur V2 X NewGen', '{}'::jsonb, 7260),
  ('chair', 'Razer', 'Razer Enki', '{}'::jsonb, 7270),
  ('chair', 'Razer', 'Razer Enki X', '{}'::jsonb, 7280),
  ('chair', 'Razer', 'Razer Enki Pro', '{}'::jsonb, 7290),
  ('chair', 'Razer', 'Razer Fujin', '{}'::jsonb, 7300),
  ('chair', 'Razer', 'Razer Fujin Pro', '{}'::jsonb, 7310),
  ('chair', 'Razer', 'Razer Soma Chroma', '{}'::jsonb, 7320)
on conflict (kind, model) do nothing;
